### ISSUE TITLE
Uncaught TypeError: Cannot redefine property: googletag

### ISSUE THREAD

**Issue by devilesk** [devilesk/dota-flashcards#1]
View details in Rollbar: [https://rollbar.com/devilesk/dota-flashcards/items/1/](https://rollbar.com/devilesk/dota-flashcards/items/1/)

```

TypeError: googletag
  File "<anonymous>", line 1, in [anonymous]
  File "<anonymous>", line 1, in [anonymous]
```

**Comment by guozimo** [comment]
Have you resolved this question ?
